version: "3.8"

services:
  backend:
    build:
      context: .
    container_name: resume-backend
    ports:
      - "8080:8080"
    volumes:
      - ./resume_folder:/app/resume_folder
      - ./output_json:/app/output_json
      - ./process_output:/app/process_output
    command: uvicorn app.main:app --host 0.0.0.0 --port 8080

  frontend:
    build:
      context: .
    container_name: resume-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./resume_folder:/app/resume_folder
      - ./output_json:/app/output_json
      - ./process_output:/app/process_output
    command: streamlit run frontend/streamlit_app.py --server.port 3000 --server.address 0.0.0.0
    depends_on:
      - backend 